### ISSUE TITLE
Ollama Docker Container Startup Errors

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#38]
## Steps to Reproduce
* Clone repo and setup properly in `docs/`
* Run GPU spin up by running `npm run start`

### Error
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
Error: failed to start containers: ollama
```

This might be a result of the new ollama docker container release a 2 days ago.
Will be investigating.

Need to run for debugging:
* `systemctl stop docker`
* `dockerd --debug`
* `docker start ollama`

**Comment by kevinthedang** [comment]
Possible temporary solution? @JT2M0L3Y 

Simply just revert to an older version of the container and see? Otherwise we are cooked with this new container and should make an issue on the official GitHub.

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/67223d1d-e4a3-4eb2-8a9e-7bcfaf986615)

**Comment by JT2M0L3Y** [comment]
Looking at the Ollama GitHub I was able to pull version 0.1.31. After making sure this was the only ollama container available, I was able to spin up both containers successfully!

![image](https://github.com/kevinthedang/discord-ollama/assets/67881240/6006abe4-1bf0-4c8b-bb75-94206738df99)

That is to say, I "rolled forward" one version instead of rolling back.
I will check next if the 0.1.30 version is working yet.

**Comment by JT2M0L3Y** [comment]
I believe this issue has been fixed. I am going to assume the fix was to run the commands initally listed from the server to restart the docker service.

Both versions (0.1.31 and 0.1.30) now work successfully with the `npm run start` command.
![image](https://github.com/kevinthedang/discord-ollama/assets/67881240/53a89e62-2071-49ad-a20f-9b18a4714be5)

**Comment by kevinthedang** [comment]
Seems like this is somehow still an issue, reopening this issue.

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/a2803e99-5948-457f-95c8-5b7f47cf0cbb)

**Comment by kevinthedang** [comment]
Seems like this is an issue with the Nvidia Drivers or the version of the Nvidia Container Toolkit. Seems like the current solution is to restart the server. Likely to investigate later.

**Comment by kevinthedang** [comment]
Alright I suppose there is no issue right now. Might just be a server issue!

**Comment by SGFGOV** [comment]
This issue still exists.. NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    On  |   00000000:00:1E.0 Off |                    0 |
|  0%   24C    P8             10W /  300W |       1MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found

**Comment by kevinthedang** [comment]
Hello @SGFGOV!

Do you mind sharing what **version** of the application you are using and what **system** it is being run on? Also, have you followed the [docker-setup](https://github.com/kevinthedang/discord-ollama/blob/master/docs/setup-docker.md) documentation? 

My initial assumptions are that Nvidia Container Toolkit might not be installed on the system or nvidia was not set as the default runtime as mentioned in the [Nvidia Container Toolkit](https://github.com/kevinthedang/discord-ollama/blob/master/docs/setup-docker.md) docs.

Specific step in [docker-setup.md](https://github.com/kevinthedang/discord-ollama/blob/master/docs/setup-docker.md#nvidia-container-toolkit-setup).

Please let me know!

cc: @JT2M0L3Y
